"""
Streamlined Radiology Reporting Assistant
Focus: Templates, Technique, and Structured Reporting
"""

import streamlit as st
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from io import BytesIO
import re
import json
import os
import datetime
import hashlib
from collections import defaultdict

# ===== CONFIGURATION =====
TEMPLATES_FILE = "saved_templates.json"

# ===== TEMPLATE SYSTEM =====
class TemplateSystem:
    """Template system for managing report templates."""
    
    def __init__(self):
        self.templates = {}
        self.load_templates()
    
    def load_templates(self):
        """Load templates from file."""
        if os.path.exists(TEMPLATES_FILE):
            try:
                with open(TEMPLATES_FILE, 'r') as f:
                    self.templates = json.load(f)
            except:
                self.templates = {}
    
    def save_templates(self):
        """Save templates to file."""
        try:
            with open(TEMPLATES_FILE, 'w') as f:
                json.dump(self.templates, f, indent=2)
        except:
            pass
    
    def add_template(self, name, content, template_type="findings"):
        """Add a new template."""
        self.templates[name] = {
            "content": content,
            "type": template_type,
            "created_by": st.session_state.get('current_user', 'unknown'),
            "created_date": datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
            "used_count": 0
        }
        self.save_templates()
    
    def get_template_heading(self, template_name):
        """Get heading format for a template."""
        if template_name not in self.templates:
            return template_name.upper()
        
        template = self.templates[template_name]
        template_type = template.get("type", "findings")
        
        heading_map = {
            "technique": "TECHNIQUE",
            "findings": "FINDINGS",
            "impression": "IMPRESSION"
        }
        
        return heading_map.get(template_type, template_name.upper())
    
    def apply_template(self, template_name, current_text=""):
        """Apply a template with proper heading."""
        if template_name not in self.templates:
            return current_text
        
        template = self.templates[template_name]
        heading = self.get_template_heading(template_name)
        
        # Increment usage count
        template["used_count"] = template.get("used_count", 0) + 1
        self.save_templates()
        
        # Format with heading
        formatted_template = f"\n{heading}:\n{template['content']}"
        
        if current_text:
            return current_text + formatted_template
        return formatted_template
    
    def get_user_templates(self, username):
        """Get templates created by specific user."""
        user_templates = {}
        for name, data in self.templates.items():
            if data.get("created_by") == username:
                user_templates[name] = data
        return user_templates

def create_word_document(report_text, technique_info, report_date):
    """Create a Word document with proper formatting."""
    doc = Document()
    
    # Title
    title = doc.add_heading('RADIOLOGY REPORT', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add spacing
    doc.add_paragraph()
    
    # Add technique section
    doc.add_heading('TECHNIQUE', level=1)
    if technique_info:
        doc.add_paragraph(f"Modality: {technique_info.get('modality', 'Not specified')}")
        doc.add_paragraph(f"Contrast: {technique_info.get('contrast', 'Without contrast')}")
        if technique_info.get('sequences'):
            doc.add_paragraph(f"Protocol: {technique_info['sequences']}")
    
    # Add spacing
    doc.add_paragraph()
    
    # Parse and add report sections
    lines = report_text.split('\n')
    
    for line in lines:
        line_stripped = line.strip()
        if not line_stripped:
            doc.add_paragraph()
            continue
            
        # Check if line is a heading (uppercase and ends with colon)
        if line_stripped.endswith(':') and line_stripped[:-1].replace(' ', '').isupper():
            heading_text = line_stripped[:-1]
            doc.add_heading(heading_text, level=1)
        else:
            # Regular content
            doc.add_paragraph(line_stripped)
    
    # Add footer
    doc.add_page_break()
    doc.add_heading('REPORT DETAILS', level=1)
    p = doc.add_paragraph()
    p.add_run(f"Generated by: {st.session_state.get('current_user', 'Unknown')}\n")
    p.add_run(f"Generation date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    return doc

def ensure_proper_structure(text):
    """Ensure report has proper FINDINGS and IMPRESSION structure."""
    if not text:
        return text
    
    # Ensure FINDINGS section exists
    if "FINDINGS:" not in text.upper():
        lines = text.split('\n')
        # Find where to insert FINDINGS
        insert_index = 0
        for i, line in enumerate(lines):
            if line.strip().startswith("TECHNIQUE:"):
                insert_index = i + 1
                while insert_index < len(lines) and lines[insert_index].strip():
                    insert_index += 1
                break
        
        if insert_index < len(lines):
            lines.insert(insert_index, "\nFINDINGS:\n")
        else:
            lines.append("\nFINDINGS:\n")
        
        text = '\n'.join(lines)
    
    # Ensure IMPRESSION section exists
    if "IMPRESSION:" not in text.upper():
        text += "\n\nIMPRESSION:\nFindings as described above. Clinical correlation recommended."
    
    return text

# ===== INITIALIZE SESSION STATE =====
def init_session_state():
    """Initialize session state variables."""
    if 'initialized' not in st.session_state:
        st.session_state.initialized = True
        st.session_state.users = {
            "admin": {"password": hashlib.sha256("admin123".encode()).hexdigest(), "role": "admin"},
            "radiologist": {"password": hashlib.sha256("rad123".encode()).hexdigest(), "role": "radiologist"}
        }
        st.session_state.report_history = []
        st.session_state.report_draft = ""
        st.session_state.ai_report = ""
        st.session_state.report_date = ""
        st.session_state.current_user = "default"
        st.session_state.logged_in = False
        st.session_state.template_system = TemplateSystem()
        st.session_state.technique_info = {
            "modality": "MRI",
            "contrast": "Without contrast",
            "sequences": "Standard sequences"
        }

# ===== STREAMLIT APP =====
def main():
    # Page config
    st.set_page_config(
        page_title="Radiology Reporting Assistant",
        layout="wide",
        page_icon="🏥"
    )
    
    # Initialize session state
    init_session_state()
    
    # ===== LOGIN SYSTEM =====
    if not st.session_state.logged_in:
        st.title("🔐 Radiology Assistant - Login")
        
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            with st.container(border=True):
                st.subheader("Login")
                username = st.text_input("Username", key="login_user")
                password = st.text_input("Password", type="password", key="login_pass")
                
                if st.button("Login", type="primary", use_container_width=True):
                    hashed_pw = hashlib.sha256(password.encode()).hexdigest()
                    if username in st.session_state.users:
                        if st.session_state.users[username]["password"] == hashed_pw:
                            st.session_state.logged_in = True
                            st.session_state.current_user = username
                            st.success(f"Welcome, {username}!")
                            st.rerun()
                        else:
                            st.error("Invalid password")
                    else:
                        st.error("User not found")
                
                st.info("Demo: admin/admin123 or radiologist/rad123")
        
        return
    
    # ===== MAIN APPLICATION =====
    
    # Header
    st.title("🏥 Radiology Reporting Assistant")
    
    col_user1, col_user2 = st.columns([3, 1])
    with col_user1:
        st.markdown(f"**User:** {st.session_state.current_user}")
    with col_user2:
        if st.button("🚪 Logout", use_container_width=True):
            st.session_state.logged_in = False
            st.rerun()
    
    # Main columns
    col1, col2 = st.columns([1, 1])
    
    with col1:
        # ===== LEFT PANEL: INPUT & TEMPLATES =====
        st.header("✍️ Report Creation")
        
        # Technique Information
        with st.expander("🔬 Technique Details", expanded=True):
            col_tech1, col_tech2 = st.columns(2)
            with col_tech1:
                modality = st.selectbox(
                    "Modality",
                    ["MRI", "CT", "Ultrasound", "X-ray", "PET-CT", "Mammography"],
                    key="modality_select"
                )
                
                contrast = st.selectbox(
                    "Contrast Administration",
                    ["Without contrast", "With contrast", "With and without contrast", "Not specified"],
                    key="contrast_select"
                )
            
            with col_tech2:
                sequences = st.text_area(
                    "Sequences/Protocol",
                    value=st.session_state.technique_info.get('sequences', ''),
                    placeholder="e.g., T1, T2, FLAIR, DWI, ADC",
                    key="sequences_input",
                    height=80
                )
            
            if st.button("💾 Save Technique", key="save_tech_button", use_container_width=True):
                st.session_state.technique_info = {
                    "modality": modality,
                    "contrast": contrast,
                    "sequences": sequences if sequences else "Standard sequences"
                }
                st.success("Technique details saved!")
        
        # Template Management
        st.divider()
        st.header("📚 Templates")
        
        # Add New Template
        with st.expander("➕ Add New Template", expanded=False):
            new_template_name = st.text_input(
                "Template Name", 
                placeholder="e.g., Normal Brain MRI Findings",
                key="new_template_name"
            )
            
            new_template_type = st.selectbox(
                "Template Type",
                ["findings", "technique", "impression"],
                format_func=lambda x: x.upper(),
                key="new_template_type"
            )
            
            new_template_content = st.text_area(
                "Template Content",
                height=150,
                placeholder="Enter the template text here...",
                key="new_template_content"
            )
            
            if st.button("💾 Save Template", type="primary", use_container_width=True, key="save_template"):
                if new_template_name and new_template_content:
                    st.session_state.template_system.add_template(
                        new_template_name,
                        new_template_content,
                        new_template_type
                    )
                    st.success(f"Template '{new_template_name}' saved!")
                    st.rerun()
                else:
                    st.warning("Please fill in both name and content")
        
        # Available Templates
        user_templates = st.session_state.template_system.get_user_templates(st.session_state.current_user)
        
        if user_templates:
            st.subheader("Your Templates:")
            for name, data in user_templates.items():
                col_temp1, col_temp2 = st.columns([3, 1])
                with col_temp1:
                    st.write(f"**{name}**")
                    st.caption(f"Type: {data.get('type', 'unknown').upper()} | Used: {data.get('used_count', 0)} times")
                with col_temp2:
                    if st.button("📥", key=f"insert_{name}", help=f"Insert {name}"):
                        st.session_state.report_draft = st.session_state.template_system.apply_template(
                            name,
                            st.session_state.report_draft
                        )
                        st.success(f"Template '{name}' inserted!")
                        st.rerun()
        else:
            st.info("No templates yet. Create your first template above!")
        
        # Quick Templates
        st.divider()
        st.subheader("⚡ Quick Templates")
        
        quick_templates = {
            "Normal Brain MRI": "No acute intracranial hemorrhage, mass effect, or territorial infarct. Ventricles and sulci are normal. No abnormal enhancement.",
            "White Matter Changes": "Scattered punctate FLAIR hyperintensities in the periventricular and deep white matter, consistent with chronic microvascular ischemic changes.",
            "Disc Herniation": "Disc bulge/protrusion causing mild neural foraminal narrowing without significant cord compression."
        }
        
        quick_selected = st.selectbox("Select:", ["Select..."] + list(quick_templates.keys()))
        
        if quick_selected != "Select...":
            if st.button(f"Insert '{quick_selected}'", use_container_width=True):
                st.session_state.report_draft += f"\nFINDINGS:\n{quick_templates[quick_selected]}"
                st.success("Template inserted!")
                st.rerun()
    
    with col2:
        # ===== RIGHT PANEL: DRAFTING & FINAL REPORT =====
        st.header("📝 Report Drafting")
        
        # Draft text area
        draft_text = st.text_area(
            "Type your report below:",
            value=st.session_state.report_draft,
            height=300,
            key="draft_input",
            label_visibility="collapsed",
            placeholder="Start typing your report here...\n\nUse 'FINDINGS:' and 'IMPRESSION:' headings."
        )
        st.session_state.report_draft = draft_text
        
        # Action buttons
        col_btn1, col_btn2, col_btn3 = st.columns(3)
        with col_btn1:
            if st.button("🤖 Generate Report", type="primary", use_container_width=True):
                if draft_text:
                    # Ensure proper structure
                    formatted_report = ensure_proper_structure(draft_text)
                    
                    # Add technique section at the beginning
                    final_report = "TECHNIQUE:\n"
                    tech_info = st.session_state.technique_info
                    final_report += f"Modality: {tech_info.get('modality', 'Not specified')}\n"
                    final_report += f"Contrast: {tech_info.get('contrast', 'Without contrast')}\n"
                    if tech_info.get('sequences'):
                        final_report += f"Protocol: {tech_info['sequences']}\n"
                    
                    final_report += "\n" + formatted_report
                    
                    st.session_state.ai_report = final_report
                    st.session_state.report_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
                    st.success("Report generated with proper structure!")
                else:
                    st.warning("Please enter some findings first")
        
        with col_btn2:
            if st.button("🔍 Check Structure", use_container_width=True):
                if "FINDINGS:" in draft_text.upper():
                    st.success("✓ FINDINGS section found")
                else:
                    st.warning("Missing FINDINGS section")
                
                if "IMPRESSION:" in draft_text.upper():
                    st.success("✓ IMPRESSION section found")
                else:
                    st.warning("Missing IMPRESSION section")
        
        with col_btn3:
            if st.button("🧹 Clear Draft", use_container_width=True):
                st.session_state.report_draft = ""
                st.rerun()
        
        # Final Report Display
        st.divider()
        st.header("📋 Final Report")
        
        if st.session_state.ai_report:
            # Display final report
            st.text_area(
                "Generated Report:",
                value=st.session_state.ai_report,
                height=350,
                key="report_preview",
                label_visibility="collapsed"
            )
            
            # Create Word document
            try:
                doc = create_word_document(
                    report_text=st.session_state.ai_report,
                    technique_info=st.session_state.technique_info,
                    report_date=st.session_state.report_date
                )
                
                # Save to buffer
                buffer = BytesIO()
                doc.save(buffer)
                buffer.seek(0)
                
                # Download button
                timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
                
                st.download_button(
                    label="📄 Download as Word Document",
                    data=buffer,
                    file_name=f"RadReport_{timestamp}.docx",
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    use_container_width=True,
                    type="primary"
                )
                
            except Exception as e:
                st.error(f"Error creating document: {str(e)}")
            
            # Save to history
            st.divider()
            report_name = st.text_input(
                "Save as:",
                value=f"Report_{st.session_state.report_date.split()[0]}",
                key="report_name"
            )
            
            if st.button("💾 Save to History", use_container_width=True):
                history_entry = {
                    "name": report_name,
                    "date": st.session_state.report_date,
                    "technique_info": st.session_state.technique_info,
                    "report": st.session_state.ai_report,
                    "created_by": st.session_state.current_user
                }
                st.session_state.report_history.append(history_entry)
                st.success("Saved to history!")
        
        else:
            # Empty state
            with st.container(border=True):
                st.info("""
                **Ready to generate your report!**
                
                1. Set technique details
                2. Use templates or type directly
                3. Ensure you have **FINDINGS:** and **IMPRESSION:** sections
                4. Click 'Generate Report'
                5. Download as Word document
                
                **Required Structure:**
                - TECHNIQUE section (auto-added)
                - FINDINGS section (your observations)
                - IMPRESSION section (conclusions)
                """)
    
    # ===== REPORT HISTORY =====
    st.divider()
    st.header("📜 Recent Reports")
    
    if st.session_state.report_history:
        for i, report in enumerate(reversed(st.session_state.report_history[-5:])):
            with st.expander(f"{report['name']} - {report['date']}", expanded=False):
                col_h1, col_h2 = st.columns([1, 1])
                with col_h1:
                    if st.button(f"📥 Load", key=f"load_{i}", use_container_width=True):
                        st.session_state.technique_info = report['technique_info']
                        st.session_state.ai_report = report['report']
                        st.session_state.report_date = report['date']
                        st.success("Report loaded!")
                        st.rerun()
                
                with col_h2:
                    report_idx = len(st.session_state.report_history) - 1 - i
                    if st.button(f"🗑️ Delete", key=f"delete_{i}", use_container_width=True):
                        st.session_state.report_history.pop(report_idx)
                        st.warning("Report deleted!")
                        st.rerun()
                
                # Show preview
                preview = report['report'][:200] + "..." if len(report['report']) > 200 else report['report']
                st.text(preview)
    else:
        st.info("No reports in history yet. Generate and save your first report!")

# ===== RUN APPLICATION =====
if __name__ == "__main__":
    main()
